/** C5.2 — Barril dos componentes do design system. */

export { Texto } from './Texto';
export type { TextoProps } from './Texto';
export { Tela } from './Tela';
export type { TelaProps } from './Tela';
export { Botao } from './Botao';
export type { BotaoProps, VarianteBotao } from './Botao';
export { CampoTexto } from './CampoTexto';
export type { CampoTextoProps } from './CampoTexto';
export { Cartao } from './Cartao';
export type { CartaoProps } from './Cartao';
export { GradienteLinear } from './GradienteLinear';
export type { GradienteLinearProps } from './GradienteLinear';
export { CartaoEconomia } from './CartaoEconomia';
export type { CartaoEconomiaProps } from './CartaoEconomia';
export { CartaoStat } from './CartaoStat';
export type { CartaoStatProps } from './CartaoStat';
export { CabecalhoVoltar } from './CabecalhoVoltar';
export type { CabecalhoVoltarProps } from './CabecalhoVoltar';
export { MolduraCamera } from './MolduraCamera';
export type { MolduraCameraProps } from './MolduraCamera';
export { VeredictoBadge } from './VeredictoBadge';
export type { VeredictoBadgeProps } from './VeredictoBadge';
export { BarraPreco } from './BarraPreco';
export type { BarraPrecoProps } from './BarraPreco';
export { Estado } from './Estado';
export type { EstadoProps, EstadoAcao } from './Estado';
export { Esqueleto } from './Esqueleto';
export type { EsqueletoProps } from './Esqueleto';
export { GraficoLinha } from './GraficoLinha';
export type { GraficoLinhaProps } from './GraficoLinha';
export { ColetorNotaWeb } from './ColetorNotaWeb';
export type { ColetorNotaWebProps, ResultadoColeta } from './ColetorNotaWeb';
export { ProvedorToast, useToast } from './Toast';
export { FolhaInferior, LinhaFolha } from './FolhaInferior';
export type { FolhaInferiorProps } from './FolhaInferior';
export { Dialogo } from './Dialogo';
export type { DialogoProps } from './Dialogo';
export { DURACAO, useDuracao, useReduzirMovimento } from './movimento';
export { Eyebrow, TituloTela, TileIcone, CartaoLista, LinhaLista } from './layout3a';
export type { LinhaListaProps } from './layout3a';
export * from './icones';
