-- Auditoria — desempate estável para o cursor do delta sync (C4.2).
--
-- O PROBLEMA. `upsertEstatisticas` carimba o MESMO `atualizado_em` em todas as
-- linhas de um lote (um `now()` por chamada). O sync ordenava só por
-- `atualizado_em`, cortava no limite de linhas e devolvia como cursor o maior
-- valor visto; a chamada seguinte filtrava com `>` esse valor. Se o corte caísse
-- DENTRO de um grupo de timestamp idêntico, o resto do grupo era pulado — e
-- pulado para sempre, porque o cursor já tinha passado dele. O cliente ficava
-- com um cache silenciosamente incompleto (veredito velho, sem erro nenhum).
--
-- A CORREÇÃO. Uma coluna monotônica de desempate transforma a paginação em
-- keyset ((atualizado_em, seq) > (cursor_ts, cursor_seq)) — determinística e sem
-- buraco, mesmo com milhares de linhas no mesmo instante.
--
-- `seq` NÃO muda no update do upsert (só nasce com a linha), então serve apenas
-- como desempate dentro de um mesmo `atualizado_em` — a ordem de recência
-- continua sendo dada por `atualizado_em`, como antes.

alter table public.preco_estatistica
  add column if not exists seq bigint generated by default as identity;

comment on column public.preco_estatistica.seq is
  'Desempate monotônico do cursor de delta sync (C4.2). Ordem real é (atualizado_em, seq).';

-- Substitui o índice só-por-atualizado_em como caminho da varredura do sync:
-- cobre o ORDER BY (atualizado_em, seq) do keyset sem sort adicional.
create index if not exists preco_estatistica_atualizado_seq_idx
  on public.preco_estatistica (atualizado_em, seq);

-- Os índices por recorte (escopo/produto) ganham o mesmo desempate — o sync
-- quase sempre filtra por município ou por produtos do histórico.
create index if not exists preco_estatistica_escopo_atualizado_seq_idx
  on public.preco_estatistica (escopo_id, atualizado_em, seq);

create index if not exists preco_estatistica_produto_atualizado_seq_idx
  on public.preco_estatistica (produto_canonico_id, atualizado_em, seq);
